version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"


phases:
  install:
       runtime-versions:
          java: corretto8

  build:
    commands:

      - mvn install

artifacts:
  files:
    - '/root/.m2/**/*'
    name: teachmemaster-1.0.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
