DROP TABLE IF EXISTS TEACHERS;

CREATE TABLE `TEACHERS` (
	`teacher_id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`student_id` INT(11) NULL DEFAULT NULL,
	`update_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`create_date` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`teacher_id`)
);
