DROP TABLE IF EXISTS TEACHERS;

CREATE TABLE `TEACHERS` (
	`teacher_id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`update_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`create_date` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`teacher_id`)
);

CREATE TABLE `STUDENTS` (
    `student_id` INT(11) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `create_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`student_id`)
);


CREATE TABLE `TEACHERS_STUDENTS`(
    `student_id` INT(11) NOT NULL,
    `teacher_id` INT(11) NOT NULL,
    FOREIGN KEY (teacher_id) REFERENCES TEACHERS (teacher_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (student_id) REFERENCES STUDENTS (student_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY (teacher_id, student_id)
);
